version: '3.9'

volumes:
  mysql_volume:

services:

  zookeeper:
    build:
      context: ./docker/zookeeper
      dockerfile: ./Dockerfile
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    build:
      context: ./docker/kafka
      dockerfile: ./Dockerfile
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306